ifeq ($(CONFIG_ARCH_PINEAPPLE),y)
include $(srctree)/techpack/bt-kernel/config/pineapplebt.conf
endif

ifeq ($(CONFIG_MSM_BT_POWER),m)
KBUILD_CPPFLAGS += -DCONFIG_MSM_BT_POWER
endif

ifeq ($(CONFIG_BTFM_SLIM),m)
KBUILD_CPPFLAGS += -DCONFIG_BTFM_SLIM
endif

ifeq ($(CONFIG_I2C_RTC6226_QCA),m)
KBUILD_CPPFLAGS += -DCONFIG_I2C_RTC6226_QCA
endif

ifeq ($(CONFIG_SLIM_BTFM_CODEC), m)
KBUILD_CPPFLAGS += -DCONFIG_SLIM_BTFM_CODEC
endif

ifeq ($(CONFIG_BT_HW_SECURE_DISABLE), y)
KBUILD_CPPFLAGS += -DCONFIG_BT_HW_SECURE_DISABLE
endif

ifeq ($(CONFIG_BTFM_SWR),m)
KBUILD_CPPFLAGS += -DCONFIG_BTFM_SWR
endif

ifeq ($(CONFIG_FMD_ENABLE), y)
KBUILD_CPPFLAGS += -DCONFIG_FMD_ENABLE
endif

ifeq ($(CONFIG_SPI_CNSS_PROTO),m)
KBUILD_CPPFLAGS += -DCONFIG_SPI_CNSS_PROTO
endif

obj-y += pwr/
obj-y += slimbus/
obj-y += rtc6226/
obj-y += btfmcodec/
obj-y += slimbus/
obj-y += soundwire/
obj-y += spi/
