#define CONFIG_MSM_BT_POWER 1
#define CONFIG_I2C_RTC6226_QCA 1
#define CONFIG_BTFM_CODEC 1
#define CONFIG_FMD_ENABLE 1
#define CONFIG_BTFM_SWR 1
#define CONFIG_BTFM_SLIM 1
#define CONFIG_SPI_CNSS_PROTO 1
