# SPDX-License-Identifier: GPL-2.0-only

include $(SPU_ROOT)/config/gki_spu.conf
LINUXINCLUDE += -include $(SPU_ROOT)/config/gki_spuconf.h

LINUXINCLUDE += -I$(srctree)/techpack/spu-kernel/include/uapi

obj-m += drivers/spcom.o
obj-m += drivers/spss_utils.o

BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/spcom.ko
BOARD_VENDOR_KERNEL_MODULES += $(KERNEL_MODULES_OUT)/spss_utils.ko
